#构造一下配置文件
server:
  port: 9002

spring:
  application:
    #    项目的名称（微项目的名称
    name: xdclass-coupon-service
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: 192.168.31.99:8848

  #消息队列
  rabbitmq:
    host: 192.168.31.99
    port: 5672
    virtual-host: /
    password: password
    username: admin
    #开启手动确认消息
    listener:
      simple:
        acknowledge-mode: manual

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xdclass_coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: abc123456
  #    redis配置
  redis:
    host: 192.168.31.99
    port: 8000
    password: 123456
#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

# Seata配置
#seata:
#  enabled: true
#  # 事务分组配置
#  tx-service-group: xdclass-coupon-service-group
#  # 指定事务分组至集群映射关系，集群名default需要与seata-server注册到Nacos的cluster保持一致
#  service:
#    vgroup-mapping:
#      xdclass-coupon-service-group: default
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      # nacos 服务地址
#      server-addr: 192.168.31.99:8848
#      namespace:
#      group: SEATA_GROUP

#自定义消息队列配置，发送锁定库存消息-》延迟exchange-》lock.queue-》死信exchange-》release.queue
mqconfig:
  #延迟队列，不能被监听消费
  coupon_release_delay_queue: coupon.release.delay.queue

  #延迟队列的消息过期后转发的队列
  coupon_release_queue: coupon.release.queue

  #交换机
  coupon_event_exchange: coupon.event.exchange

  #进入延迟队列的路由key
  coupon_release_delay_routing_key: coupon.release.delay.routing.key

  #消息过期，进入释放死信队列的key
  coupon_release_routing_key: coupon.release.routing.key

  #消息过期时间,毫秒,测试改为15秒
  ttl: 15000
